### PR TITLE
Fix syntax error due to use of non-transformable ES6 "new.target"

### LINKED ISSUE #45: "SyntaxError: Unexpected token ." due to use of "new.target"
On older versions of Node.js (such as 4.7 on AWS Lambda), "new.target" does not exist and cannot be transformed using Babel v6 (https://github.com/babel/babel/issues/1088). Because of this, the following line results in test and runtime failures:

https://github.com/cubehouse/themeparks/blob/master/lib/park.js#L72

Given that the supported Node.js version [in your `package.json` file](https://github.com/cubehouse/themeparks/blob/master/package.json#L21) reads `>=0.12`, this should be fixed to allow for the Babel built file to be run on older versions of Node.js.

The earliest version of Node.js that supports `new.target` is 5.0.0: https://nodejs.org/en/blog/release/v5.0.0/

The same functionality can be achieved through the use of `this.constructor` (note that `this.constructor` does not allow for all the same use cases as `new.target`, but it does satisfy the use case of preventing this base class from being constructed directly).

### PR DESCRIPTION
**Pull request by andrewmunsell**
"new.target" is used to ensure that the base class cannot be instantiated directly, but this is an ES6 feature new to Node.js v5.0.0 that cannot be transformed directly by Babel v6 (https://github.com/babel/babel/issues/1088) and results in a syntax error in versions of Node.js <5.0.0. This change fixes the issue using this.constructor and ensures that the script properly runs on older versions of Node.js when Babel is used to build the dist files.

This also adjusts the Travis CI Node.JS versions to include Node.JS 4 and 0.12, which are listed as supported in the package.json file.

Fixes #45

### CODE REVIEW

File: lib/test.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ try {
         it("should not create the park base successfully", function(done) {
             try {
                 parkBase = new Park();
-                assert(parkBase, "parkBase should not successfully construct");
```
Comment (andrewmunsell) [inline lib/test.js]: Note that this test used to not work at all-- if the base park *was* created successfully, the assert statement would have passed.
